baseurl:
title: Rebecca Harris
description: UX and UI Designer with a secret love of CSS.
permalink: /:categories/:title/
google_analytics_code: UA-31980509-7
defaults:
  - scope:
      type: posts
    values:
      layout: post
      published: true
  - scope:
      type: work
    values:
      layout: default
      published: true
collections:
  work:
    output: true
    permalink: /work/:path/
prose:
  rooturl: "_posts"
  media: "assets/uploads"
  siteurl: "http://www.rebeccadianeharris.com"
  metadata:
    _posts:
      - name: "published"
        field:
          element: 'hidden'
          value: true
      - name: "title"
        field:
          element: "text"
          label: "title"
