baseurl: http://becbec1.github.io
title: Rebecca Diane Harris
description: All Things Visual
permalink: /:categories/:title/
google_analytics_code:
defaults:
  -
    scope:
      type: "posts"
    values:
      layout: "default"
      published: true
prose:
  rooturl: "_posts"
  media: "assets/uploads"
  siteurl: "http://www.rebeccadianeharris.com"
  metadata:
    _posts:
      - name: "published"
        label: "Published"
        field:
          element: 'select'
          options:
            - name: 'true'
              value: true
            - name: 'false'
              value: false
      - name: "title"
        field:
          element: "text"
          label: "title"
