baseurl: http://becbec1.github.io
title: Rebecca Diane Harris
description: All Things Visual
permalink: /:categories/:title/
google_analytics_code:
defaults:
  -
    scope:
      type: "posts"
    values:
      layout: "default"
prose:
  rooturl: "_posts"
  media: "assets/uploads"
  siteurl: "http://www.rebeccadianeharris.com"
